name: Deploy Medusa to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ secrets.ECR_REPO_URL }}

      - name: Build and push Docker image to ECR
        run: |
          docker build -t ${{ secrets.ECR_REPO_URL }}:latest .
          docker push ${{ secrets.ECR_REPO_URL }}:latest

      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER_NAME }} \
            --service ${{ secrets.ECS_SERVICE_NAME }} \
            --force-new-deployment \
            --region ${{ secrets.AWS_REGION }}
